refactor: implement encapsulation
DevCrew-io/FhotoEditor pull request #2
Opened 2023-03-15 09:14 UTC by arslandevcrew

Implement Abstract class to hide the functionality.

2023-03-15 09:27 UTC, WaseemAbbas-DevCrew requested changes
Please see my comments and do the relevant changes

2023-03-15 09:27 UTC, WaseemAbbas-DevCrew commented on lib/features/cropping/image_crop.dart
write documentation for all methods

2023-03-15 10:27 UTC, arslandevcrew commented
![](https://github.trello.services/images/mini-trello-icon.png) [code documentation](https://trello.com/c/INelToYq/12-code-documentation)

2023-03-16 13:27 UTC, WaseemAbbas-DevCrew approved these changes

2023-03-16 13:28 UTC, merged